### ISSUE TITLE
DPS3005 no response

### ISSUE THREAD

**Issue by CommanderRedYT** [syssi/esphome-dps#21]
![image](https://github.com/syssi/esphome-dps/assets/43087936/93a2e7c5-9079-4922-8a6e-ab002034209f)

I have connected a ESP32 (NodeMCU-32 V1.3) to a DPS3005. Mine came without a connector, but i just soldered some cables to it. 

I double-checked all connections, tried to switch RX and TX, tried different Pins but still, it does not work...

**Comment by syssi** [comment]
Which GPIOs did you use as RX/TX pins? Could you provide a photo of your wiring and the configuration YAML?

**Comment by CommanderRedYT** [comment]
I wired it like this: https://johan.kanflo.com/wp-content/uploads/2017/06/DPS5005-comms-UART.jpg (Not my picture, but is same as i have)

**Comment by CommanderRedYT** [comment]
Okay, somehow it is working now. Did not change anything tho.
